const imageGallery = [
  {
    id: 1,
    location: "Sài Gòn",
    title: "Sunset at the beach",
    description: "A beautiful sunset at the beach in Saigon",
    src: "https://source.unsplash.com/VWcPlbHglYc",
    tag: "Saigon",
  },
  {
    id: 2,
    location: "Vũng Tàu",
    title: "Coastal landscape",
    description: "A stunning view of the coast in Vung Tau",
    src: "https://source.unsplash.com/FV3GConVSss",
    tag: "VungTau",
  },
  {
    id: 3,
    location: "Sài Gòn",
    title: "City skyline",
    description: "A beautiful view of Saigon at night",
    src: "https://source.unsplash.com/e6FMMambeO4",
    tag: "Saigon",
  },
  {
    id: 4,
    location: "Tây Ninh",
    title: "Countryside landscape",
    description: "A scenic view of the countryside in Tay Ninh",
    src: "https://source.unsplash.com/klCiPmzUw0Y",
    tag: "TayNinh",
  },
  {
    id: 5,
    location: "Tây Ninh",
    title: "Rice fields",
    description: "A beautiful view of rice fields in Tay Ninh",
    src: "https://source.unsplash.com/IdNOTjPeHrE",
    tag: "TayNinh",
  },
  {
    id: 6,
    location: "Tây Ninh",
    title: "Mountain landscape",
    description: "A beautiful view of the mountains in Tay Ninh",
    src: "https://source.unsplash.com/O0N9MF--hK4",
    tag: "TayNinh",
  },
  {
    id: 7,
    location: "Vũng Tàu",
    title: "Seaside view",
    description: "A stunning view of the seaside in Vung Tau",
    src: "https://source.unsplash.com/DqyYTM7pR2o",
    tag: "VungTau",
  },
];
export default imageGallery;
